### ISSUE TITLE
天气接口

### ISSUE THREAD

**Issue by zane001** [iQuick/SunDay#1]
http://m.weather.com.cn/atad/  这个查询六天内的天气接口已经无法使用。

**Comment by zane001** [comment]
目前可以使用 http://113.108.239.116/atad/

**Comment by iQuick** [comment]
谢谢，已经修改，亲，你是怎么发现这个接口的

**Comment by wzxwater** [comment]
现在中国天气也已经不提供查询六天的天气接口了。
